apps/videos/urls.py
from django.conf.urls import patterns, url

from videos.views import ListVideos, push_stat

urlpatterns = patterns('videos.views',
    url(r'^list_all/$', ListVideos.as_view(), name='videos_list'),
    url(r'^push_stat/$', push_stat, name='push_stat'),
)

video_test/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'video_test.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^videos/', include('videos.urls', namespace='videos')),
    
)

apps/videos/models.py
from django.db import models

# Create your models here.

class Video(models.Model):

    video_id = models.CharField(max_length=200, unique=True)

    def __unicode__(self):
        return "https://www.youtube.com/watch?v=%s" % self.video_id


class VideoStat(models.Model):
    video = models.ForeignKey(Video)
    loads = models.IntegerField(max_length=200, default=0)
    plays = models.IntegerField(max_length=200, default=0)

apps/videos/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from django.views.decorators.http import require_POST
from django.http import HttpResponse

from videos.models import Video, VideoStat


class ListVideos(ListView):

    model = Video
    template_name = 'videos/player.html'


@require_POST
def push_stat(request):
    post = request.POST
    video_id = post.get('video_id')
    stat_type = post.get('stat_type')

    video = Video.objects.get(video_id=video_id)
    vid_stat, created = VideoStat.objects.get_or_create(video=video)
    if stat_type == "loads":
        vid_stat.loads += 1
    elif stat_type == "plays":
        vid_stat.plays += 1

    vid_stat.save()

    return HttpResponse()

apps/templates/videos/player.html
{% load bootstrap3 %}
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>

    <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'js/ajax_csrf_preset.js' %}"></script>
    <script>

      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      function onYouTubeIframeAPIReady() {
        {% for video in object_list %}
            //TODO: In real case it's better to load video_id throw ajax
             player = new YT.Player('player{{ video.id }}', {
                height: '500',
                width: '100%',
                videoId: '{{ video.video_id }}',
                events: {
                  'onReady': onPlayerReady,
                  'onStateChange': onPlayerStateChange
                }
                });
        {% endfor %}
        
      }

      function getVideoId(url){
        var match = url.match(/[?&]v=([^&]+)/);
        return match[1];
      }

      function onPlayerReady(event) {
        var url = event.target.getVideoUrl();
        var video_id = getVideoId(url);
        console.log("video "+video_id+" loaded");
        $.post( 
          "{% url 'videos:push_stat'%}", 
          {
            "video_id": video_id, 
            "stat_type":"loads" 
          }
        );
      }

      var done = new Object();

      function onPlayerStateChange(event) {
        var url = event.target.getVideoUrl();
        var video_id = getVideoId(url);
        if (event.data == YT.PlayerState.PLAYING && !done[video_id]) {
          console.log("state for video "+video_id+" changed");
          $.post( 
            "{% url 'videos:push_stat'%}", 
            {
              "video_id": video_id, 
              "stat_type":"plays" 
            }
          );
          done[video_id] = true;
        }
        
      }
    </script>
  </head>
  <body>
      <div class="container">
        <div class="span8">
        <div id="myCarousel" class="carousel slide">
          <ol class="carousel-indicators">
          {% for video in object_list %}
            <li data-target="#myCarousel" data-slide-to="{{forloop.counter0}}" class="{% if forloop.first %} active {% endif %}"></li>
          {% endfor %}
          </ol>
          <div class="carousel-inner">
          {% for video in object_list %}
            <div class="item {% if forloop.first %} active {% endif %}" style="padding-left: 15%; padding-right: 15%;">
              <div id="player{{ video.id }}"></div>
            </div>
          {% endfor %}
          </div>
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
        </div>
        </div>
      </div>
  </body>
</html>